version: '3.8'

services:
  # work manager
  onedep_workmanager:
    image: dockerhub.ebi.ac.uk/wwpdb/py-wwpdb_apps_workmanager:docker
    environment:
      TOP_WWPDB_SITE_CONFIG_DIR: /wwpdb/onedep/site-config
      WWPDB_SITE_ID: ${WWPDB_SITE_ID}
      WWPDB_SITE_LOC: ${WWPDB_SITE_LOC}
    ports:
      - target: 8080
        published: 8080
    volumes:
      - onedep_data:/wwpdb/onedep/data
      - onedep_sessions:/wwpdb/onedep/sessions
      - onedep_resources_ro:/wwpdb/onedep/resources_ro
      - type: bind
        source: ./env/site-config
        target: /wwpdb/onedep/site-config

volumes:
  onedep_data:
  onedep_sessions:
  onedep_reference:
  onedep_webapps:
  onedep_resources_ro: